version: "3"
services:
  iac-dev-container:
    container_name: IaCDevContainer
    image: ghcr.io/maxotta/iac-development-container:latest
    volumes:
      - "iac-dev-container-data:/var/iac-dev-container-data"
      - "../..:/workspace"
  localstack:
    container_name: "LocalStack"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack-container-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  iac-dev-container-data:
    external: false
  localstack-container-data:
    external: false

